#################################################################
#                        General Settings                       #
#                                                               #
#    If you want maximum performance (TPS), be sure to set      #
#    the collector mode to INSTANT, and holograms to false.     #
#                                                               #
#################################################################

# The title of the collector GUI.
title: 'ChunkCollector'

# The amount of inventory slots. (minimum: 27)
size: 27

# The mode of the collector. Either: FALL_DEATH, INSTANT
mode: INSTANT

# Enable or disable collector holograms.
holograms: true

#################################################################
#                   Add & Customize Collectors                  #
#                                                               #
#             You can create as many custom collectors          #
#         as you want, name them differently and support        #
#          different drops (mob drops, farm drops, etc.)        #
#                                                               #
#################################################################

# Here are the two default collectors. Feel free to use them as templates
# to build your own custom chunk collectors. Also, if you want an item
# to have no lore, simply set the lore option to NONE.
collectors:
  farm:
    item-name: '&bFarm Collector'
    background: NONE
    SUGAR_CANE:
      slot: 11
      name: '&fSugarcane'
      lore: NONE
      pricePer: 175
    WHEAT:
      slot: 13
      name: '&fWheat'
      lore: NONE
      pricePer: 175
    CACTUS:
      slot: 15
      name: '&fCactus'
      lore: NONE
      pricePer: 175
  mob:
    item-name: '&6Mob Collector'
    background: BLACK
    BLAZE_ROD:
      slot: 10
      name: '&fBlaze Rod'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 100
    BONE:
      slot: 11
      name: '&fBone'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 100
    SULPHUR:
      slot: 12
      name: '&fGunpowder'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
    ARROW:
      slot: 13
      name: '&fArrow'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
    SPIDER_EYE:
      slot: 14
      name: '&fSpider Eye'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
    ROTTEN_FLESH:
      slot: 15
      name: '&fRotten Flesh'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 125
    STRING:
      slot: 16
      name: '&fString'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 125

#################################################################
#                           Messages                            #
#                                                               #
#       Customize every message in the plugin to fit your       #
#                server's style and colors.                     #
#                                                               #
#################################################################

# General messages.
no-permission: '&cYou do not have permission to do this.'
incorrect-syntax: '&cIncorrect syntax, please try again.'
reload-config: '&aYou reloaded the configuration file.'
player-not-found: '&cCould not find the specified player.'
must-have-faction: '&cYou must be in a faction to do this.'
chunk-occupied: '&cThere is already a %type% &cin this chunk.'

# Collector messages.
collector-place: '&aYou placed: %type%'
collector-place-failure: '&cYou cannot place a chunk collector here.'
collector-break: '&cYou removed: %type%'
collector-break-failure: '&aYou are not allowed to break this chunk collector.'
collector-sell: '&aSuccessfully sold &f%amount%x %name% &afor &f$%price%.'
collector-invalid: '&cThe collector you specified cannot be found.'
collector-give: '&aYou gave %name%: %type% &fx %amount%&a'
collector-receive: '&aYou received: %type% &fx %amount%&a'
collector-deny: '&cYou must be atleast %rank% &cto do this.'

#################################################################
#                        Placeable Item                         #
#                                                               #
#       This section is for customizing the actual item that    #
#            people will be placing in their bases.             #
#                                                               #
#################################################################

collector:
  type: HOPPER
  glowing: true
  lore:
    - ''
    - '&rPlace this down in your &eclaimed land &fto'
    - '&rstart collecting &emob &f& &efarm &fdrops.'
    - '&rYou can use the sell wands to quickly sell your savings.'