#################################################################
#                   General Settings + Layout                   #
#                                                               #
#     Customize the collectors by adding or removing mobs to    #
#      your liking. You can create as many custom collectors    #
#         as you want, name them differently and support        #
#          different drops (mob drops, farm drops, etc.)        #
#                                                               #
#################################################################

title: 'ChunkCollector'
size: 45

# The mode of the collector. Either: FALL_DEATH, INSTANT
mode: INSTANT

# Here you create your custom collectors. To help you get started, I made two default collectors.
collectors:
  farm_collector:
    background: NONE
    SUGAR_CANE:
      slot: 1
      name: '&fSugarcane'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
  mob_collector:
    background: BLACK
    BONE:
      slot: 20
      name: '&fBone'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 100
    ARROW:
      slot: 22
      name: '&fArrow'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
    ROTTEN_FLESH:
      slot: 24
      name: '&fRotten Flesh'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 125


#################################################################
#                           Messages                            #
#                                                               #
#       Customize every message in the plugin to fit your       #
#                server's style and colors.                     #
#                                                               #
#################################################################

# General messages.

no-permission: '&cYou do not have permission to access this.'
incorrect-syntax: '&cIncorrect syntax, please try again.'
reload-config: '&aYou reloaded the configuration file.'
player-not-found: '&cCould not find the specified player.'

# Collector messages.

collector-place: '&aYou placed the chunk collector.'
collector-place-failure: '&aYou cannot place a chunk collector here.'
collector-break: '&aYou removed the chunk collector.'
collector-break-failure: '&aYou are not allowed to break this chunk collector.'
collector-sell: '&aSuccessfully sold &f%amount%x %name% &afor &f$%price%.'

#################################################################
#                        Placeable Item                         #
#                                                               #
#       This section is for customizing the actual item that    #
#            people will be placing in their bases.             #
#                                                               #
#################################################################

collector:
  name: 'ChunkCollector'
  type: BEACON
  glowing: true
  lore:
    - '&rPlace this down in your &eclaimed land &fto'
    - '&rstart collecting &emob &f& &efarm &fdrops.'
    - '&rYou can use the sell wands to quickly sell your savings.'
    - '&r'
    - '&4&lNOTICE: &rYou must be %rank%+ to use.'