#################################################################
#                        General Settings                       #
#                                                               #
#    If you want maximum performance (TPS), be sure to set      #
#    the collector mode to INSTANT, and holograms to false.     #
#                                                               #
#################################################################

# The title of the collector GUI.
title: 'ChunkCollector'

# The amount of inventory slots. (minimum: 27)
size: 45

# The mode of the collector. Either: FALL_DEATH, INSTANT
mode: INSTANT

# Enable or disable collector holograms.
holograms: true

# Toggle the TNT bank feature. (SavageFactions ONLY)
tnt-bank: false

# When set to true, normal cactus farms will not grow. Forces player to use collector.
disable-natural-farms: true

# How often are collector backup files created? (default: every 5 minutes)
collector-backup-interval: 5

# Enable or disable a runnable to cleanup any collectors removed by WorldEdit, Trench Pickaxe, etc.
cleanup-runnable: true

#################################################################
#                   Add & Customize Collectors                  #
#                                                               #
#             You can create as many custom collectors          #
#         as you want, name them differently and support        #
#          different drops (mob drops, farm drops, etc.)        #
#                                                               #
#################################################################

# Here are the two default collectors. Feel free to use them as templates
# to build your own custom chunk collectors. Also, if you want an item
# to have no lore, simply set the lore option to NONE.
collectors:
  farm:
    item-name: '&bFarm Collector'
    background: NONE
    SUGAR_CANE:
      slot: 11
      name: '&fSugarcane &8(&7%amount%&8)'
      lore: NONE
      pricePer: 175
    WHEAT:
      slot: 13
      name: '&fWheat &8(&7%amount%&8)'
      lore: NONE
      pricePer: 175
    CACTUS:
      slot: 15
      name: '&fCactus &8(&7%amount%&8)'
      lore: NONE
      pricePer: 175
  mob:
    item-name: '&6Mob Collector'
    background: BLACK
    RAW_CHICKEN:
      slot: 10
      name: '&fChicken &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 0.9375
    FEATHER:
      slot: 11
      name: '&fFeather &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 1.875
    PORK:
      slot: 12
      name: '&fRaw Pork &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 0.9375
    RAW_BEEF:
      slot: 13
      name: '&fRaw Beef &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 1.25
    LEATHER:
      slot: 14
      name: '&fLeather &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 4.375
    MUTTON:
      slot: 15
      name: '&fRaw Mutton &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 0.9375
    WOOL:
      slot: 16
      name: '&fWool &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 1.25
    ROTTEN_FLESH:
      slot: 19
      name: '&fRotten Flesh &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 2.1875
    ARROW:
      slot: 20
      name: '&fArrow &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 2.1875
    BONE:
      slot: 21
      name: '&fBone &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 2.1875
    SPIDER_EYE:
      slot: 22
      name: '&fSpider Eye &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 2.5
    STRING:
      slot: 23
      name: '&fString &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 2.5
    TNT:
      slot: 24
      name: '&fTNT &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 6.875
    GOLD_NUGGET:
      slot: 25
      name: '&fGold Nugget &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 8.3
    BLAZE_ROD:
      slot: 29
      name: '&fBlaze Rod &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 17.5
    SLIME_BALL:
      slot: 30
      name: '&fSlime Ball &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 12.5
    ENDER_PEARL:
      slot: 31
      name: '&fEnder Pearl &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 15
    IRON_INGOT:
      slot: 32
      name: '&fIron Ingot &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 35
    EMERALD:
      slot: 33
      name: '&fEmerald &8(&7%amount%&8)'
      lore:
      - '&7Value: &a$%value%'
      - ''
      - '&aLeft-click to sell.'
      - '&6Right-click to extract.'
      pricePer: 150

#################################################################
#                           Messages                            #
#                                                               #
#       Customize every message in the plugin to fit your       #
#                server's style and colors.                     #
#                                                               #
#################################################################

# General messages.
no-permission: '&cYou do not have permission to do this.'
incorrect-syntax: '&cIncorrect syntax, please try again.'
reload-config: '&aYou reloaded the configuration file.'
player-not-found: '&cCould not find the specified player.'
must-have-faction: '&cYou must be in a faction to do this.'
chunk-occupied: '&cThere is already a %type% &cin this chunk.'

# Collector messages.
collector-place: '&aYou placed: %type%'
collector-place-failure: '&cYou cannot place a chunk collector here.'
collector-break: '&cYou removed: %type%'
collector-break-failure: '&cYou are not allowed to break this chunk collector.'
collector-sell: '&aSuccessfully sold %name% &afor &f$%price%.'
collector-invalid: '&cThe collector you specified cannot be found.'
collector-give: '&aYou gave %name%: %type% &fx %amount%&a'
collector-receive: '&aYou received: %type% &fx %amount%&a'
collector-deny: '&cYou must be atleast %rank% &cto do this.'
collector-extract: '&aYou extracted: %name%'

#################################################################
#                        Placeable Item                         #
#                                                               #
#       This section is for customizing the actual item that    #
#            people will be placing in their bases.             #
#                                                               #
#################################################################

collector:
  type: HOPPER
  glowing: true
  lore:
    - ''
    - '&rPlace this down in your &eclaimed land &fto'
    - '&rstart collecting &ecustom&f drops.'