#################################################################
#                        General Settings                       #
#                                                               #
#    If you want maximum performance (TPS), be sure to set      #
#    the collector mode to INSTANT, and holograms to false.     #
#                                                               #
#################################################################

# The title of the collector GUI.
title: 'ChunkCollector'

# The amount of inventory slots. (minimum: 27)
size: 45

# The mode of the collector. Either: FALL_DEATH, INSTANT
mode: INSTANT

# Enable or disable collector holograms.
holograms: true

#################################################################
#                   Add & Customize Collectors                  #
#                                                               #
#             You can create as many custom collectors          #
#         as you want, name them differently and support        #
#          different drops (mob drops, farm drops, etc.)        #
#                                                               #
#################################################################

collectors:
  farm:
    item-name: '&bFarm Collector'
    background: NONE
    SUGAR_CANE:
      slot: 1
      name: '&fSugarcane'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
  mob:
    item-name: '&6Mob Collector'
    background: BLACK
    BONE:
      slot: 20
      name: '&fBone'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 100
    ARROW:
      slot: 22
      name: '&fArrow'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 175
    ROTTEN_FLESH:
      slot: 24
      name: '&fRotten Flesh'
      lore:
      - '&aLeft-click to sell.'
      pricePer: 125

#################################################################
#                           Messages                            #
#                                                               #
#       Customize every message in the plugin to fit your       #
#                server's style and colors.                     #
#                                                               #
#################################################################

# General messages.
no-permission: '&cYou do not have permission to do this.'
incorrect-syntax: '&cIncorrect syntax, please try again.'
reload-config: '&aYou reloaded the configuration file.'
player-not-found: '&cCould not find the specified player.'
must-have-faction: '&cYou must be in a faction to do this.'
chunk-occupied: '&cThere is already a %type% &cin this chunk.'

# Collector messages.
collector-place: '&aYou placed: %type%'
collector-place-failure: '&cYou cannot place a chunk collector here.'
collector-break: '&cYou removed: %type%'
collector-break-failure: '&aYou are not allowed to break this chunk collector.'
collector-sell: '&aSuccessfully sold &f%amount%x %name% &afor &f$%price%.'
collector-invalid: '&cThe collector you specified cannot be found.'
collector-give: '&aYou gave %name%: %type% &fx %amount%&a'
collector-receive: '&aYou received: %type% &fx %amount%&a'
collector-deny: '&cYou must be atleast %rank% &cto do this.'

#################################################################
#                      Permission Settings                      #
#                                                               #
#       Here you can edit all of the collector permission       #
#               settings to your server's style.                #
#         (0 = RECRUIT, 1 = NORMAL, 2 = MODERATOR, etc.)        #
#                                                               #
#################################################################

permissions:
  place-collector: 2
  destroy-collector: 2
  sell-collector: 2

#################################################################
#                        Placeable Item                         #
#                                                               #
#       This section is for customizing the actual item that    #
#            people will be placing in their bases.             #
#                                                               #
#################################################################

collector:
  type: HOPPER
  glowing: true
  lore:
    - ''
    - '&rPlace this down in your &eclaimed land &fto'
    - '&rstart collecting &emob &f& &efarm &fdrops.'
    - '&rYou can use the sell wands to quickly sell your savings.'