name: ChunkCollectors
version: 2.8.9
author: Cloth
main: com.cloth.ChunkCollectorPlugin
depends: [Factions]
commands:
  collector:
    description: Displays the available chunk collector commands.
    aliases: [chunkcollector]
